### ISSUE TITLE
6桁の認証コードを入力後にエラーが表示され認証ができない

### ISSUE THREAD

**Issue by ShinKuroda2** [edginer/eddiner#16]
**バグの概要**
6桁の認証コードを入力後に下記エラーが表示される
「認証に失敗しました

Reason: 認証コード、もしくはIPアドレスが一致しません」

**再現方法**
1.JaneXeno x64 230826 でエッジ版の任意のスレッドに書き込み
2.表示された6桁のコードを認証URLのページに書き込む
3.バグの概要に記載したエラーが表示される

**本来あるべき振る舞い**
エラーが表示されず認証が成功すること

**スクリーンショット**
バグに関連するスクリーンショットが添付可能な場合は、添付を行ってください
https://puu.sh/K3YCw/9ad0498662.zip

**実行環境**
以下を参考に埋めてください
 - Windows10 Pro 22H2
 - JaneXeno x64
 - 230826

**その他**
何かあれば

**Comment by edginer** [comment]
こちらに関してはひとまずのところWebブラウザ上で書き込み、認証を行うなどして得られたトークンを利用して専用ブラウザ上で書き込んでいただくようお願いします

**Comment by ShinKuroda2** [comment]
承知しました。
上記処理で書き込みは可能なのでクローズします。
